### ISSUE TITLE
HDRI image not loading

### ISSUE THREAD

**Issue by Felixoofed** [PyExplained/3D-Renderer#3]
the HDRI image is not loading although i specified a path

**Comment by Felixoofed** [comment]
the render just gives me a white image

**Comment by PyExplained** [comment]
Hi, could you show me the code, please? Something that might be going on, is that the renderer does not use the right values for the brightness of the image and thus outputs white. Maybe you can try converting the image into a '.jpg' format (even though some information will be lost)?

**Comment by Felixoofed** [comment]
ill try
